

# 1.Importing pandas

In [2]:
import pandas as pd

In [12]:
df = pd.read_csv('heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

# 2.opening using a url

In [13]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/adityanath123/data_factory1/refs/heads/https/github.com/adityanath123/insurance.csv"
headers = {"User-Agent": "Mozilla/5.0(Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url,headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

# 3. sep parameter

In [14]:
pd.read_csv('mtcars.tsv',sep='/t',names=['name'])

C:\Users\yadav\AppData\Local\Temp\ipykernel_18264\2715952114.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd.read_csv('mtcars.tsv',sep='/t',names=['name'])

                                                 name
0   Mazda RX4\t21\t6\t160\t110\t3.9\t2.62\t16.46\t...
1   Mazda RX4 Wag\t21\t6\t160\t110\t3.9\t2.875\t17...
2   Datsun 710\t22.8\t4\t108\t93\t3.85\t2.32\t18.6...
3   Hornet 4 Drive\t21.4\t6\t258\t110\t3.08\t3.215...
4   Hornet Sportabout\t18.7\t8\t360\t175\t3.15\t3....
5   Valiant\t18.1\t6\t225\t105\t2.76\t3.46\t20.22\...
6   Duster 360\t14.3\t8\t360\t245\t3.21\t3.57\t15....
7   Merc 240D\t24.4\t4\t146.7\t62\t3.69\t3.19\t20\...
8   Merc 230\t22.8\t4\t140.8\t95\t3.92\t3.15\t22.9...
9   Merc 280\t19.2\t6\t167.6\t123\t3.92\t3.44\t18....
10  Merc 280C\t17.8\t6\t167.6\t123\t3.92\t3.44\t18...
11  Merc 450SE\t16.4\t8\t275.8\t180\t3.07\t4.07\t1...
12  Merc 450SL\t17.3\t8\t275.8\t180\t3.07\t3.73\t1...
13  Merc 450SLC\t15.2\t8\t275.8\t180\t3.07\t3.78\t...
14  Cadillac Fleetwood\t10.4\t8\t472\t205\t2.93\t5...
15  Lincoln Continental\t10.4\t8\t460\t215\t3\t5.4...
16  Chrysler Imperial\t14.7\t8\t440\t230\t3.23\t5....
17  Fiat 128\t32.4\t4\t78.7\t66\t4.08\t2.2\t19.47\...
18  Honda Civic\t30.4\t4\t75.7\t52\t4.93\t1.615\t1...
19  Toyota Corolla\t33.9\t4\t71.1\t65\t4.22\t1.835...
20  Toyota Corona\t21.5\t4\t120.1\t97\t3.7\t2.465\...
21  Dodge Challenger\t15.5\t8\t318\t150\t2.76\t3.5...
22  AMC Javelin\t15.2\t8\t304\t150\t3.15\t3.435\t1...
23  Camaro Z28\t13.3\t8\t350\t245\t3.73\t3.84\t15....
24  Pontiac Firebird\t19.2\t8\t400\t175\t3.08\t3.8...
25  Fiat X1-9\t27.3\t4\t79\t66\t4.08\t1.935\t18.9\...
26  Porsche 914-2\t26\t4\t120.3\t91\t4.43\t2.14\t1...
27  Lotus Europa\t30.4\t4\t95.1\t113\t3.77\t1.513\...
28  Ford Pantera L\t15.8\t8\t351\t264\t4.22\t3.17\...
29  Ferrari Dino\t19.7\t6\t145\t175\t3.62\t2.77\t1...
30  Maserati Bora\t15\t8\t301\t335\t3.54\t3.57\t14...
31  Volvo 142E\t21.4\t4\t121\t109\t4.11\t2.78\t18....

# 4.Index_col parameter

In [15]:
pd.read_csv('insurance.csv',index_col='charges')

             age     sex     bmi  children smoker     region
charges
16884.92400   19  female  27.900         0    yes  southwest
1725.55230    18    male  33.770         1     no  southeast
4449.46200    28    male  33.000         3     no  southeast
21984.47061   33    male  22.705         0     no  northwest
3866.85520    32    male  28.880         0     no  northwest
...          ...     ...     ...       ...    ...        ...
10600.54830   50    male  30.970         3     no  northwest
2205.98080    18  female  31.920         0     no  northeast
1629.83350    18  female  36.850         0     no  southeast
2007.94500    21  female  25.800         0     no  southwest
29141.36030   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

# 6. header format

In [16]:
pd.read_csv('heart.csv',header=1)

     40  M  ATA  140  289  0  Normal  172  N  0.1    Up  0.2
0    49  F  NAP  160  180  0  Normal  156  N  1.0  Flat    1
1    37  M  ATA  130  283  0      ST   98  N  0.0    Up    0
2    48  F  ASY  138  214  0  Normal  108  Y  1.5  Flat    1
3    54  M  NAP  150  195  0  Normal  122  N  0.0    Up    0
4    39  M  NAP  120  339  0  Normal  170  N  0.0    Up    0
..   .. ..  ...  ...  ... ..     ...  ... ..  ...   ...  ...
912  45  M   TA  110  264  0  Normal  132  N  1.2  Flat    1
913  68  M  ASY  144  193  1  Normal  141  N  3.4  Flat    1
914  57  M  ASY  130  131  0  Normal  115  Y  1.2  Flat    1
915  57  F  ATA  130  236  0     LVH  174  N  0.0  Flat    1
916  38  M  NAP  138  175  0  Normal  173  N  0.0    Up    0

[917 rows x 12 columns]

# use_cols parameter

In [17]:
pd.read_csv('insurance.csv',usecols=['smoker','age','children'])

      age  children smoker
0      19         0    yes
1      18         1     no
2      28         3     no
3      33         0     no
4      32         0     no
...   ...       ...    ...
1333   50         3     no
1334   18         0     no
1335   18         0     no
1336   21         0     no
1337   61         0    yes

[1338 rows x 3 columns]

# 8. Squeeze parameters

In [18]:
#pd.read_csv('insurance.csv',usecols=['region'],squeeze=True
region = pd.read_csv('insurance.csv')['region']
region

0       southwest
1       southeast
2       southeast
3       northwest
4       northwest
          ...
1333    northwest
1334    northeast
1335    southeast
1336    southwest
1337    northwest
Name: region, Length: 1338, dtype: str

# 9. skiprows/nrows Parameter

In [20]:
pd.read_csv('insurance.csv',#skiprows=[0,2]
           nrows=100)

    age     sex     bmi  children smoker     region      charges
0    19  female  27.900         0    yes  southwest  16884.92400
1    18    male  33.770         1     no  southeast   1725.55230
2    28    male  33.000         3     no  southeast   4449.46200
3    33    male  22.705         0     no  northwest  21984.47061
4    32    male  28.880         0     no  northwest   3866.85520
..  ...     ...     ...       ...    ...        ...          ...
95   28  female  37.620         1     no  southeast   3766.88380
96   54  female  30.800         3     no  southwest  12105.32000
97   55    male  38.280         0     no  southeast  10226.28420
98   56    male  19.950         0    yes  northeast  22412.64850
99   38    male  19.300         0    yes  southwest  15820.69900

[100 rows x 7 columns]

# 10. Encoding parameter

In [6]:
pd.read_csv('zomato.csv',encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

# 11. skip bad lines

In [9]:
#pd.read_csv('BX-Books.csv', sep=';', encoding="latin-1",error_bad_lines=False)
import pandas as pd

books = pd.read_csv(
    'BX-Books.csv',
    sep=';',
    encoding='latin-1',
    on_bad_lines='skip'
)

print(books.head())

  isbn,book_title,book_author,year_of_publication,publisher
0  195153448,Classical Mythology,Mark P. O. Morfo...
1  2005018,Clara Callan,Richard Bruce Wright,2001...
2  60973129,Decision in Normandy,Carlo D'Este,199...
3  374157065,Flu: The Story of the Great Influenz...
4  399135782,The Kitchen God's Wife,Amy Tan,1991,...

# 12 . dtypes parameter

In [15]:
#pd.read_csv('insurance.csv',dtype={'bmi':int}).info()

# 13 . handling dates

In [16]:
parse_dates=['date']

# 14. convertors

In [17]:
# (convertors= {'column_name':rename})

# 15 . na_values para meter

In [18]:
# kisi values ko (NaN) ke form mr kar dena jaise ki 
# (sampel.csv,na_value=['sampleword'])

# 16. Loding a huge data set in chunks

In [24]:
dfs = pd.read_csv('heart.csv',chunksize=5000)

In [28]:

import pandas as pd

dfs = pd.read_csv("insurance.csv", chunksize=200)

for chunk in dfs:
    print(chunk.shape) 
dfs

(200, 7)
(200, 7)
(200, 7)
(200, 7)
(200, 7)
(200, 7)
(138, 7)

In [29]:
dfs